title: "Statistics Homework"
tagline: "Alessandro Maone - 1945149"
description: "Homework collection for the university course in Statistics"
author:
  name: "Alessandro Maone - 1945149"
  url: "https://github.com/alexgallo8"

permalink: /:title/

# URL del sito
baseurl: ""
url: "https://alexgallo8.github.io"

markdown: kramdown
paginate: 5
paginate_path: "page:num"

# Excerpt settings
excerpt_length: 50
excerpt_separator: "<!--more-->"