title: "Statistics Homework"
tagline: "Assignments for the Statistics course"
description: "Homework collection for the university course in Statistics, published via Jekyll + Lanyon theme."
author:
  name: "Tuo Nome"
  url: "https://github.com/tuo-username"

permalink: /:title/

# URL del sito
baseurl: ""
url: "https://tuo-username.github.io"

markdown: kramdown
paginate: 5
paginate_path: "page:num"